'''
APPLICATION WIDE CONSTANT
'''
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


MIN_PASSWORD_LENGTH = 8
PASSWORD_RESET_TTL_HOURS = 1
EMAIL_VERIFY_TTL_HOURS = 24
JWT_ACCESS_TTL_SECONDS = 60*60
JWT_REFRESH_TTL_SECONDS = 60*60*24*7


EARTH_RADIUS_KM = 6371.0088
DEG_PER_KM_LAt = 1.0/111.0
DEFAULT_SEARCH_RADIUS_KM = 15.0
MAX_SEARCH_RADIUS_KM = 500.0



DEFAULT_FREQUENCY_HZ = 50
DEFAULT_BASE_MA = 100.0
DEFAULT_POWER_FACTOR = 0.9
DEFAULT_VOLTAGE_TOL_PU = 0.05
DEFAULT_LINE_LOADING_PCT = 100.0


STANDARD_VOLTAGES_KV = (
    0.4,11.0,22.0,33.0,66.0,110.0,132.0,220.0,400.0,765.0,
)


SIZE_THRESHOLD_SMALL_MW = 1.0
SIZE_THRESHOLD_MEDIUM_MW = 10.0
SIZE_THRESHOLD_LARGE_MW = 50.0


LOAD_FLOW_MAX_ITERATION = 50
LOAD_FLOW_TOLERANCE_MVA = 1e-8
SHORT_CIRCUIT_LEVEL_TOL_PERCENT  = 10.0
TIME_SERIES_MAX_STEPS = 8760

FEASIBILITY_MIN_HEADROOM_FACTOR = 1.2
FEASIBILITY_MAX_VOLTAGE_DROP_PCT = 5.0
FEASIBILITY_DEFAULT_DETOUR = 1.3
FEASIBILITY_SC_STIFFNESS_RATIO= 10.0


FREE_TIER = {
    "max_networks":            3,
    "max_buses_per_network":   50,
    "max_analyses_per_month":  20,
    "max_reports_per_month":   5,
    "max_facilities":          5,
    "max_org_members":         1,
}


DEFAULT_REPORT_FOLDER = 'reports'
MAX_REPORT_SIZE_MB = 25
SUPPORTED_REPORT_FORMATS = ("pdf","xlsx")


SIO_NAMESPACE              = "/analysis"
SIO_EVENT_JOB_QUEUED       = "job_queued"
SIO_EVENT_JOB_STARTED      = "job_started"
SIO_EVENT_JOB_PROGRESS     = "job_progress"
SIO_EVENT_JOB_COMPLETED    = "job_completed"
SIO_EVENT_JOB_FAILED       = "job_failed"
SIO_EVENT_JOB_CANCELLED    = "job_cancelled"
SIO_EVENT_FEASIBILITY_DONE = "feasibility_completed"
SIO_EVENT_REPORT_READY     = "report_ready"





RESOURCE_USER         = "user"
RESOURCE_NETWORK      = "power_network"
RESOURCE_FACILITY     = "facility"
RESOURCE_SUBSTATION   = "substation"
RESOURCE_ANALYSIS_JOB = "analysis_job"
RESOURCE_REPORT       = "report"
RESOURCE_ORGANIZATION = "organization"
RESOURCE_PLAN         = "plan"
RESOURCE_SUBSCRIPTION = "subscription"